### ISSUE TITLE
Where's the download of the finished build?

### ISSUE THREAD

**Issue by James103** [aole/ClothSimulator#3]
I've been looking across some of your profiles, hoping to find a website or a link to download the build of this, but I couldn't after about an hour of Google searching. I also tried compiling it myself, but failed. I want to experiment with this, which was why I went looking.

Do you have the finished build available? If so, where is it? If not, are you willing to compile a build of this for me or will I have to compile it myself?

**Comment by aole** [comment]
I don't have a build and haven't compiled this in a while now. Its not in a state that it does anything remotely useful.
If you want to compile, I can help you with that.
